### ISSUE TITLE
cannot find hackmd related command

### ISSUE THREAD

**Issue by allenhooocl** [hackmdio/vscode-hackmd#21]
after installed the hackmd extension, how can I open preview using hackmd's markdown renderer?

**Comment by Yukaii** [comment]
Hi @allenhooocl , we extended VSCode's built-in Markdown Preview now, so just use the command: "Markdown: Open Preview" or "Markdown: Open preview to the side".

**Comment by Yukaii** [comment]
Feel free to reopen the issue if you still encounter any problem :)

**Comment by allenhooocl** [comment]
Well noted, it works, thanks.
