### ISSUE TITLE
Can not edit in read-only editor

### ISSUE THREAD

**Issue by Fashaun** [hackmdio/vscode-hackmd#42]
I can preview hackmd note successfully,

but When I want to edit note from vscode, it shows the message "Can not edit in read-only editor"

**Comment by NeverTeaser** [comment]
+1

**Comment by NeverTeaser** [comment]
@Fashaun I just restart the extension, It's worked

**Comment by Fashaun** [comment]
what did you mean

**Comment by Fashaun** [comment]
hi , 

The issue is still here

**Comment by FavorMylikes** [comment]
+1

**Comment by FANJIYU0825** [comment]
You don't have the Authority to comit

**Comment by FANJIYU0825** [comment]
it's call for  api by hackmd.io   hope can help you solve it.
If you want add the and save  please copy and paste new page and you are the owner

**Comment by worldofgeese** [comment]
Permissions to edit given an API key don't appear to map to permissions to edit as a user on the HackMD website. That said, perhaps this is coming in a future release of the VS Code extension given this issue was closed in a commit to the `develop` branch by @Yukaii.

**Comment by luiswyss** [comment]
This issue still exists. 
Editing personal notes in VSCode works well but collaborative notes cannot be edited. It shows the message: "Editor is read-only because the file is read-only."
Note that it is perfectly possible to edit the file in browser and that I have added my HackMD API key to VSCode.

**Comment by sspaeti** [comment]
Yep I am experienceing the same. Works well for my own notes, but not with notes within a team that I have access too. As said above, works well in the web view.
