### ISSUE TITLE
Can not create new note from vscode

### ISSUE THREAD

**Issue by Fashaun** [hackmdio/vscode-hackmd#44]
![image](https://user-images.githubusercontent.com/5792071/102222359-4a1e4a80-3f1e-11eb-90a2-5422b005b7f9.png)

**Comment by Fashaun** [comment]
no it still there
 
The message is "Cannot edit in read-only editor"

**Comment by Fashaun** [comment]
Now plugin is only support create "empty" note from vscode but not edit

**Comment by Yukaii** [comment]
Editing support is still working in progress and can be tracked through https://github.com/hackmdio/vscode-hackmd/pull/92

**Comment by Fashaun** [comment]
But I still meet the following issue in latest version
https://stackoverflow.com/questions/54856374/cannot-edit-in-read-only-editor-vs-code

**Comment by Yukaii** [comment]
Yes, that's what we intended to do for now. The editing support is not released yet.
