### ISSUE TITLE
please co-publish on open-vsx

### ISSUE THREAD

**Issue by GitMensch** [hackmdio/vscode-hackmd#50]
Please make this extension available to [Open VSX](https://github.com/eclipse/openvsx) marketplace, this will also make it directly available for [VSCodium](https://vscodium.com/) and [Gitpod](https://www.gitpod.io/).
 
> Open VSX is a [vendor-neutral](https://projects.eclipse.org/projects/ecd.openvsx) open-source alternative to the [Visual Studio Marketplace](https://marketplace.visualstudio.com/vscode). It provides a server application that manages [VS Code extensions](https://code.visualstudio.com/api) in a database, a web application similar to the VS Code Marketplace, and a command-line tool for publishing extensions similar to [vsce](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#vsce).

There is a [guide for publishing](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) and after the initial setup it is just a matter of `osvx publish` (similar to the MS marketplace). The previous link also provides hints to do the publishing (to both marketplaces if you like) automated via GitHub action [which, I _think_ means: just tag/release and the rest will happen automatically).

**Comment by SilvanCodes** [comment]
I would like to see that too, very much! :)

**Comment by Yukaii** [comment]
https://open-vsx.org/extension/HackMD/vscode-hackmd

We've published a version on open-vsc. We'll integrate github actions in future releases.
