### ISSUE TITLE
How to use the extension ?

### ISSUE THREAD

**Issue by KapilRakh** [hackmdio/vscode-hackmd#6]
After installing, does this extension automatically work with VS Code's built-in preview or there is anything special you need to do ? I don't see any changes in preview.

**Comment by Yukaii** [comment]
Yes, it works with VSCode markdown preview. You could try some of the HackMD markdown syntaxes, for example, **container syntax**:

```markdown
:::info
Here's the info block
:::
```

**Comment by RoyiAvital** [comment]
It seems the Extensions is configured with KaTeX.
How could one use MathJaX instead (Like in the Web Version)?

KaTeX is limited and MathJaX is much better.

Thank You.

**Comment by Yukaii** [comment]
@RoyiAvital I've open #9 for tracking this. It was not implemented at first because it's harder to bundled MathJax with webpack. We'll investigate this.
