### ISSUE TITLE
[Linux] Extension does not follow XDG spec

### ISSUE THREAD

**Issue by zjeffer** [hackmdio/vscode-hackmd#62]
According to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), the folder created by this extension is in the wrong place.

When changing hackmd settings through the vscode settings UI, it created a folder in the home directory (`/home/<user>/.hackmd/`), which clutters the home directory with unnecessary files. The folder (with the `cookies.json` file) should be in $XDG_DATA_HOME, $XDG_CONFIG_HOME, or $XDG_CACHE_HOME, I think.

**Comment by Yukaii** [comment]
The folder is no longer created because the new extension now uses access tokens for authentication.

Close this now.
