### ISSUE TITLE
markdown checkboxes shown twice in the preview, side by side

### ISSUE THREAD

**Issue by jspille** [hackmdio/vscode-hackmd#7]
Very powerful preview, but with one issue. In the preview I see each markdown checkbox twice in the preview, side by side. No - I'm not drunken, but it's look like that. 

![CheckboxInHachMDPreview](https://user-images.githubusercontent.com/11789513/72010648-8e0dc780-3258-11ea-9fd7-ccb5aae3d9c1.png)

**Comment by Yukaii** [comment]
Hi @jspille, do you install other markdown extensions in VSCode?

**Comment by jspille** [comment]
Yes, that's may be the issue. Thanks for the hint.
