### ISSUE TITLE
Login does not work - is the project maintained?

### ISSUE THREAD

**Issue by afrittoli** [hackmdio/vscode-hackmd#73]
I tried using the extension, but login against the official hackmd instance does not work. 
The latest activity on this repo seems to be from 2020 - is this project still being maintained? 
If not it would be great to update the README accordingly.

**Comment by Yukaii** [comment]
Hello, we've release a new version to the marketplace, please upgrade to the latest version.

The new extension will prompt you to enter a access token, you can generate one from [settings page](https://hackmd.io/settings#api).

https://marketplace.visualstudio.com/items?itemName=HackMD.vscode-hackmd
