### ISSUE TITLE
Log in issue will be fixed in 2~3 weeks

### ISSUE THREAD

**Issue by elek-hmd** [hackmdio/vscode-hackmd#75]
Hi users,

I'm elek, the product manager of HackMD.

Users have been unable to log in to the VSCode extension. We apologize for your hampered workflow.

The logging-in of our VSCode extension broke since we've introduced several measures into the logging-in flow to ward off bot registrations and other spam. 

We will fix this in 2～3 weeks. Instead of email and password, you will use an API token for logging in to the extension in the future.

We could have avoided this issue and have learned a lesson. We apologize for the inconvenience you might experience.

**Comment by Wavesolid** [comment]
does this issue will be resolved soon? was waiting and hoping this extension will be work again.

**Comment by Yukaii** [comment]
Hi all, we've release a new version to the marketplace, please upgrade to the latest version.

The new extension will prompt you to enter a access token, you can generate one from [settings page](https://hackmd.io/settings#api).

https://marketplace.visualstudio.com/items?itemName=HackMD.vscode-hackmd

**Comment by theluke** [comment]
Hi @Yukaii I just installed the latest vscode extension. It prompts me for username and password, not the API token, and logins fails.
Thank you

**Comment by Yukaii** [comment]
Hi @theluke

Have you tried reload the window? And can you give me a screenshot of current installed version through:

Extension panel -> Search for `@installed hackmd` -> Click on HackMD

<img width="370" alt="スクリーンショット 2023-02-20 午後8 02 52" src="https://user-images.githubusercontent.com/4230968/220101128-6a3613d9-a4d5-4342-86ec-12e28ab3164e.png">


<img width="590" alt="スクリーンショット 2023-02-20 午後8 01 27" src="https://user-images.githubusercontent.com/4230968/220101165-a63cfb8d-6f40-4fd0-8800-b2f66557643a.png">

**Comment by theluke** [comment]
Hello, my VsCode was not the latest version; I had v1.70, whilst I needed v1.75.
It works now, thank you.
On the other hand, I seem unable to EDIT existing hackmd files; is that correct?
